CREATE TYPE task_status AS ENUM('open', 'in_progress', 'completed', 'cancelled');
CREATE TYPE task_priority AS ENUM('low', 'medium', 'high', 'critical');

CREATE TABLE IF NOT EXISTS "task" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "alert_id" BIGINT,                                    
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',               
    "priority" task_priority NOT NULL DEFAULT 'low',
    "status" task_status NOT NULL DEFAULT 'open',
    "assigned_to" INT,                                    
    "due_date" TIMESTAMPTZ,                               
    "completed_at" TIMESTAMPTZ,                           
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

