CREATE TYPE alert_status AS ENUM('open', 'acknowledged', 'resolved');
CREATE TYPE alert_severity AS ENUM('low', 'medium', 'high', 'critical');

CREATE TABLE IF NOT EXISTS "alert" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "node_id" VARCHAR(255) NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "severity" alert_severity NOT NULL DEFAULT 'low',
    "status" alert_status NOT NULL DEFAULT 'open',
    "detected_at" TIMESTAMPTZ NOT NULL,
    "acknowledged_at" TIMESTAMPTZ,
    "resolved_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TRIGGER update_alert_updated_at
    BEFORE UPDATE ON "alert"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();